---
# handlers file for etcd

- name: Daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    daemon_reload: true
