---
# handlers file for patronicluster

- name: Restart pg
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true

- name: Patroni daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart patroni
  ansible.builtin.systemd:
    name: patroni
    state: restarted
